sudo: required

services:
  - docker

# what to do before running tests or deployment.
before-install:
  - docker build -t blackhat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true blackhat/docker-react npm run test